# Generated by Django 5.2 on 2025-05-01 22:41

import datetime
import django.db.models.deletion
import restaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the menu')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=200)),
                ('reservation_date', models.DateField(help_text='Date of the reservation (cannot be in the past)', validators=[restaurant.models.validate_not_past])),
                ('reservation_time', models.TimeField(default=datetime.time(12, 0), help_text='Time slot of the reservation')),
                ('party_size', models.PositiveSmallIntegerField(default=1, help_text='Number of guests')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['reservation_date', 'reservation_time'],
                'unique_together': {('reservation_date', 'reservation_time', 'first_name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_items', to='restaurant.category')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu items',
                'ordering': ['title'],
                'unique_together': {('title', 'menu')},
            },
        ),
    ]
